- name: Ensure intermediate CSR directories exist
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ pki_basepath }}/int-ca/csr"
    - "/vagrant/artifacts/certs/root-requests"

# Just because this is in a VirtualBox, and ansible
# doesn't like copying into the mounted folder, use
# a shell copy.
- name: Submit the Intermediate CSR for the Root to sign
  shell: |
    find {{ pki_basepath }}/int-ca/csr \
        -name \*.csr \
        -exec mv {} /vagrant/artifacts/certs/root-requests/ \;

- name: export certificates
  shell: |
    find {{ pki_basepath }}/int-ca/certs \
        -name \*.pem \
        -exec cp {} /vagrant/artifacts/certs/ \;
  tags: certs
