
# Some magic for the Vagrant demo.
# Copy any certificates into the CA.
- name: import certificates
  import_tasks: vagrant-to-intermediate.yml

# INTERMEDIATE CA SETUP
- name: setup intermediate CA
  import_tasks: intermediateca.yml

# Some magic for the Vagrant demo.
# Copy any requests into the Vagrant host.
- name: export requests
  import_tasks: intermediate-to-vagrant.yml
