- name: Ensure intermediate directories exist
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ pki_basepath }}/int-ca/csr"
    - "{{ pki_basepath }}/int-ca/certs"
    - "/vagrant/artifacts/certs/root-requests"

# Just because this is in a VirtualBox, and ansible
# doesn't like copying into the mounted folder, use
# a shell copy.
- name: Import the root-signed intermediate certificates
  shell: |
    find {{ item | dirname }} \
        -name {{ item | basename }} \
        -exec cp {} {{ pki_basepath }}/int-ca/certs/ \;
    find {{ pki_basepath }}/int-ca/certs \
        -name \*.pem \
        -exec chmod 0400 {} \;
  with_items:
    - "/vagrant/artifacts/certs/root.pem"
    - "/vagrant/artifacts/certs/int.pem"
